





 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("4.0.0.6")]
 [assembly: AssemblyFileVersion("4.0.0.6")]
 [assembly: AssemblyInformationalVersion("v4.0.0.6")]